#!/usr/bin/env python

import rospy
import time
from std_msgs.msg import Float64

def data(n,jdata):

    if n==1:
        j1.data=jdata
        pub1.publish(j1)
    elif n==2:
        j2.data=jdata
        pub2.publish(j2)
    elif n==3:
        j3.data=jdata
        pub3.publish(j3)
    elif n==4:
        j4.data=jdata
        pub4.publish(j4)
    elif n==5:
        j5.data=jdata
        pub5.publish(j5)
    elif n==6:
        j6.data=jdata
        pub6.publish(j6)

    print("Done")
    



rospy.init_node("sendJointsGzNode")
topic1 = '/robotfr/joint1_position_controller/command'
topic2 = '/robotfr/joint2_position_controller/command'
topic3 = '/robotfr/joint3_position_controller/command'
topic4 = '/robotfr/joint4_position_controller/command'
topic5 = '/robotfr/joint5_position_controller/command'
topic6 = '/robotfr/joint6_position_controller/command'
pub1 = rospy.Publisher(topic1, Float64, queue_size=10, latch=True)
pub2 = rospy.Publisher(topic2, Float64, queue_size=10, latch=True)
pub3 = rospy.Publisher(topic3, Float64, queue_size=10, latch=True)
pub4 = rospy.Publisher(topic4, Float64, queue_size=10, latch=True)
pub5 = rospy.Publisher(topic5, Float64, queue_size=10, latch=True)
pub6 = rospy.Publisher(topic6, Float64, queue_size=10, latch=True)

j1 = Float64(); j2 = Float64(); j3 = Float64()
j4 = Float64(); j5 = Float64(); j6 = Float64()

rate = rospy.Rate(10)
while not rospy.is_shutdown():
    data(1, -2.26)
    time.sleep(10)
    data(2,0.086)
    time.sleep(10)
    data(3, -0.26)
    time.sleep(10)
    data(4, -1.39)
    time.sleep(10)
    data(5,-0.55)
    time.sleep(10)
    break
    rate.sleep()

print "End motion ..."
