#!/usr/bin/env python

import rospy
from sensor_msgs.msg import JointState
from markers import *
from functions import *


rospy.init_node("testInvKine")
pub = rospy.Publisher('joint_states', JointState, queue_size=1000)

bmarker      = BallMarker(color['RED'])
bmarker_des  = BallMarker(color['GREEN'])

# Joint names
jnames = ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']

# Desired position
#xd = np.array([0.12, 0.125, 0.149])
#xd = np.array([0.2, 0.2, 0.179])
#xd = np.array([-0.1, 0.15, 0.3])
xd = np.array([-0.2, 0.15, 0.28])
# Initial configuration
q0 = np.array([0.0, -1.0, 1.7, -2.2, -1.6, 0.0])
# -1.75 < q[0] < 2.79
# -0.52 < q[1] < 1.22
# -2.97 < q[2] < 1.05
# -6.11 < q[3] < 6.11
# -3.58 < q[4] < 0.63
# -6.28 < q[5] < 6.28
# Inverse kinematics
q = ikine(xd, q0)

# Resulting position (end effector with respect to the base link)
T = fkine(q)
print('Obtained value:\n', np.round(T,3))

# Red marker shows the achieved position
bmarker.xyz(T[0:3,3])
# Green marker shows the desired position
bmarker_des.xyz(xd)

# Objeto (mensaje) de tipo JointState
jstate = JointState()
# Asignar valores al mensaje
jstate.header.stamp = rospy.Time.now()
jstate.name = jnames
# Add the head joint value (with value 0) to the joints
jstate.position = q

# Loop rate (in Hz)
rate = rospy.Rate(100)
# Continuous execution loop
while not rospy.is_shutdown():
    # Current time (needed for ROS)
    jstate.header.stamp = rospy.Time.now()
    # Publish the message
    pub.publish(jstate)
    bmarker.publish()
    bmarker_des.publish()
    # Wait for the next iteration
    rate.sleep()